version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
     - echo Installing dependencies...
     - export export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain nextwork --domain-owner 494713367427 --region eu-north-1 --query authorizationToken --output text`
  build:
    commands:
     - echo build started on today$(date)
     - mvn -s settings.xml compile
  post_build:
    commands:
     - echo build completed justnow $(date)
     - mvn -s settings.xml package
artifacts:
  files: 
     - target/nextwork-web-project.war
  discard-paths: no     
